### ChatGPT to generate Java code with JBang support
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{OPENAI_API_KEY}}
Content-Type: application/json

{
  "model": "gpt-4o-mini",
  "messages": [
    {
      "role": "system",
      "content": "You are an Java expert. You are writing Java code with [JBang](https://www.jbang.dev/) support. Add no additional text. Please add dependencies, javadoc in the code."
    },
    {
      "role": "user",
      "content": "Please write a simple Hello.java."
    }
  ]
}

### foojay jdk versions from distro
GET https://api.foojay.io/disco/v3.0/packages?release_status=ga&package_type=jdk&latest=available&libc_type=libc&archive_type=tar.gz&operating_system=mac&distro=temurin&architecture=x64

### SDKMAN health check
GET https://api.sdkman.io/2/healthcheck

### SDKMAN candidates list
GET https://api.sdkman.io/2/candidates/list

### SDKMAN candidate version list
GET https://api.sdkman.io/2/candidates/java/darwinx64/versions/list?installed=


### SDKMAN candidate default version
GET https://api.sdkman.io/2/candidates/default/java

### SDKMAN candidate version list
GET https://api.sdkman.io/2/candidates/ant/darwinx64/versions/list?installed=

### sdkman candidate release download url
// @no-redirect
GET https://api.sdkman.io/2/broker/download/java/22.0.2-tem/darwinx64

### maven search
GET https://search.maven.org/solrsearch/select?q=spring-messaging&rows=20&wt=json

### maven class search
GET https://search.maven.org/solrsearch/select?q=c:VelocityEngine&rows=20&wt=json
